package generator

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/neo-fs/protoc-gen-grpc-ts/internal/types"
)

// GenerateTypesFile generates the types TypeScript file
func GenerateTypesFile(gen *protogen.Plugin, file *protogen.File, target string) {
	// Check if this file has services - service files shouldn't use namespace wrappers
	// because they import types from other files with the same package namespace
	hasServices := len(file.Services) > 0
	// Use the proto file path directly for output
	protoPath := file.Desc.Path()
	// Remove .proto extension and convert to output path
	// For Node.js target, use _pb.ts suffix for service files, _types.ts for type-only files
	// We'll determine the target later, but for now use _types.ts as default
	// The actual target-specific naming will be handled in the service generator
	var outputPath string
	if hasServices {
		// Service files generate _pb.ts (messages) - this will be used by both React Native and Node.js
		// Node.js will also generate _grpc_pb.ts for services separately
		outputPath = strings.TrimSuffix(protoPath, ".proto") + "_pb.ts"
	} else {
		// Type-only files: use _pb.ts for Node.js, _types.ts for React Native
		if target == "nodejs" || target == "node" {
			outputPath = strings.TrimSuffix(protoPath, ".proto") + "_pb.ts"
		} else {
			outputPath = strings.TrimSuffix(protoPath, ".proto") + "_types.ts"
		}
	}
	g := gen.NewGeneratedFile(outputPath, file.GoImportPath)

	// Generate header
	g.P("// Code generated by protoc-gen-grpc-ts. DO NOT EDIT.")
	g.P("// Generated from: ", file.Desc.Path())
	g.P()

	// Collect all external types used in this file
	externalTypes := make(map[string]string) // package -> import path
	for _, message := range file.Messages {
		collectExternalTypes(message, file, externalTypes, target)
	}

	// Generate imports for external types (only for types files)
	GenerateImportsForTypesFile(g, file, externalTypes, target)

	// Generate type aliases for enum types from external packages
	for packageName, _ := range externalTypes {
		// Add type alias for ChecksumType if importing from refs
		if strings.Contains(packageName, "Refs") {
			g.P("type ChecksumType = ", packageName, ".ChecksumType;")
		}
	}
	if len(externalTypes) > 0 {
		g.P()
	}

	// Generate BinaryWriter and BinaryReader classes (only once per file)
	types.GenerateBinaryClasses(g)

	// Get the package name for namespace generation
	packageName := types.GetPackageName(file)

	// Start namespace if we have a package name AND this is not a service file
	// Service files import from other files with the same package, which would
	// cause namespace conflicts if we also create a namespace
	useNamespace := packageName != "" && !hasServices
	if useNamespace {
		g.P("export namespace ", packageName, " {")
		g.P()
	}

	// Generate enums first
	GenerateEnums(g, file.Enums)

	// Generate message types (including nested messages)
	GenerateMessages(g, file.Messages, file, target)

	// Close namespace if we opened one
	if useNamespace {
		g.P("} // namespace ", packageName)
	}
}

// GenerateEnums generates all enums
func GenerateEnums(g *protogen.GeneratedFile, enums []*protogen.Enum) {
	for _, enum := range enums {
		GenerateEnum(g, enum)
	}
}

// GenerateEnum generates a single enum
func GenerateEnum(g *protogen.GeneratedFile, enum *protogen.Enum) {
	g.P("export enum ", enum.GoIdent.GoName, " {")
	for _, value := range enum.Values {
		g.P("  ", value.GoIdent.GoName, " = ", value.Desc.Number(), ",")
	}
	g.P("}")
	g.P()
}

// GenerateMessages generates all messages
func GenerateMessages(g *protogen.GeneratedFile, messages []*protogen.Message, file *protogen.File, target string) {
	for _, message := range messages {
		GenerateMessage(g, message, file, target)
	}
}

// GenerateMessage generates a single message
func GenerateMessage(g *protogen.GeneratedFile, message *protogen.Message, file *protogen.File, target string) {
	messageName := message.GoIdent.GoName

	// Generate interface
	g.P("export interface ", messageName, " {")
	for _, field := range message.Fields {
		fieldName := ToCamelCase(field.GoName)
		fieldType := types.GetTypeScriptTypeForField(field, file)
		// Make message fields optional to avoid infinite recursion with self-referencing types
		if field.Desc.Kind() == protoreflect.MessageKind && !field.Desc.IsList() && !field.Desc.IsMap() {
			g.P("  ", fieldName, "?: ", fieldType, ";")
		} else {
			g.P("  ", fieldName, ": ", fieldType, ";")
		}
	}
	g.P("}")
	g.P()


	// Generate implementation class
	g.P("export class ", messageName, "Impl implements ", messageName, " {")
	for _, field := range message.Fields {
		fieldName := ToCamelCase(field.GoName)
		fieldType := types.GetTypeScriptTypeForField(field, file)
		// Make message fields optional to avoid infinite recursion with self-referencing types
		if field.Desc.Kind() == protoreflect.MessageKind && !field.Desc.IsList() && !field.Desc.IsMap() {
			g.P("  ", fieldName, "?: ", fieldType, ";")
		} else {
			g.P("  ", fieldName, "!: ", fieldType, ";")
		}
	}
	g.P()

	// Generate constructor
	g.P("  constructor(data?: Partial<", messageName, ">) {")
	for _, field := range message.Fields {
		fieldName := ToCamelCase(field.GoName)
		defaultValue := types.GetDefaultValueForField(field, file)

		g.P("    this.", fieldName, " = data?.", fieldName, " ?? ", defaultValue, ";")
	}
	g.P("  }")
	g.P()

	// Generate serializeBinary method
	g.P("  serializeBinary(): Uint8Array {")
	g.P("    const writer = new BinaryWriter();")
	g.P()
	for _, field := range message.Fields {
		GenerateFieldSerialization(g, field, file)
	}
	g.P("    return writer.getResultBuffer();")
	g.P("  }")
	g.P()

	// Generate deserializeBinary static method
	g.P("  static deserializeBinary(data: Uint8Array): ", messageName, "Impl {")
	g.P("    const reader = new BinaryReader(data);")
	g.P("    const message = new ", messageName, "Impl();")
	g.P()
	g.P("    // Parse protobuf wire format")
	g.P("    while (reader.position < reader.buffer.length) {")
	g.P("      const tag = reader.readVarint();")
	g.P("      const fieldNumber = tag >>> 3;")
	g.P("      const wireType = tag & 7;")
	g.P()
	g.P("      switch (fieldNumber) {")

	// Generate field deserialization with proper wire format parsing
	for _, field := range message.Fields {
		fieldName := ToCamelCase(field.GoName)
		fieldNumber := field.Desc.Number()

		g.P("        case ", fieldNumber, ": // ", fieldName)
		GenerateFieldDeserializationWithWireType(g, field, file)
		g.P("          break;")
	}

	g.P("        default:")
	g.P("          // Skip unknown fields")
	g.P("          reader.skipField(wireType);")
	g.P("          break;")
	g.P("      }")
	g.P("    }")
	g.P()
	g.P("    return message;")
	g.P("  }")
	g.P()

	// Generate toObject method
	// For Node.js, use the Data type alias to avoid type merging issues
	// For other targets, use the interface name directly
	returnType := messageName
	if target == "nodejs" || target == "node" {
		returnType = messageName + "Data"
	}
	g.P("  toObject(): ", returnType, " {")
	g.P("    return {")
	for i, field := range message.Fields {
		fieldName := ToCamelCase(field.GoName)
		if i < len(message.Fields)-1 {
			g.P("      ", fieldName, ": this.", fieldName, ",")
		} else {
			g.P("      ", fieldName, ": this.", fieldName)
		}
	}
	g.P("    };")
	g.P("  }")
	g.P()
	g.P("}")
	g.P()

	// For Node.js target, also export a class alias without Impl suffix for compatibility
	// This allows Node.js code to use new BalanceRequest() instead of new BalanceRequestImpl()
	// Skip class alias for reserved names like "Object" which conflict with built-in types
	if target == "nodejs" || target == "node" {
		// Check if this is a reserved name that would conflict
		isReservedName := messageName == "Object" || messageName == "Array" || messageName == "Function" || messageName == "String" || messageName == "Number" || messageName == "Boolean"
		
		if !isReservedName {
			g.P("// Export class alias without Impl suffix for Node.js compatibility")
			g.P("export class ", messageName, " extends ", messageName, "Impl {}")
			g.P()
			// Create a type that represents only the interface properties (excludes class methods)
			// This is used by toObject() to return just the data without methods
			g.P("// Type for interface data only (excludes class methods from merged type)")
			g.P("export type ", messageName, "Data = Omit<", messageName, ", 'serializeBinary' | 'toObject' | 'constructor'>;")
			g.P()
		} else {
			// For reserved names, create the Data type from the interface directly (no class merging)
			g.P("// Type for interface data only (class alias skipped for reserved name)")
			g.P("export type ", messageName, "Data = ", messageName, ";")
			g.P()
		}
	}

	// Generate nested messages and enums
	GenerateMessages(g, message.Messages, file, target)
	GenerateEnums(g, message.Enums)
}

// GenerateFieldSerialization generates field serialization code
func GenerateFieldSerialization(g *protogen.GeneratedFile, field *protogen.Field, file *protogen.File) {
	fieldName := ToCamelCase(field.GoName)
	fieldNumber := field.Desc.Number()

	// Handle repeated fields
	if field.Desc.IsList() {
		g.P("    for (const item of this.", fieldName, ") {")
		GenerateRepeatedFieldSerialization(g, field, file)
		g.P("    }")
		return
	}

	// Handle map fields
	if field.Desc.IsMap() {
		g.P("    for (const [key, value] of this.", fieldName, ".entries()) {")
		g.P("      // Map serialization not fully implemented yet")
		g.P("      // Key: key, Value: value")
		g.P("    }")
		return
	}

	// Handle regular fields
	switch field.Desc.Kind() {
	case protoreflect.DoubleKind:
		g.P("    if (this.", fieldName, " !== 0.0) {")
		g.P("      writer.writeDouble(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.FloatKind:
		g.P("    if (this.", fieldName, " !== 0.0) {")
		g.P("      writer.writeFloat(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("    if (this.", fieldName, " !== 0) {")
		g.P("      writer.writeInt32(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("    if (this.", fieldName, " !== 0n) {")
		g.P("      writer.writeInt64(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("    if (this.", fieldName, " !== 0) {")
		g.P("      writer.writeUint32(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("    if (this.", fieldName, " !== 0n) {")
		g.P("      writer.writeUint64(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.BoolKind:
		g.P("    if (this.", fieldName, " !== false) {")
		g.P("      writer.writeBool(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.StringKind:
		g.P("    if (this.", fieldName, " !== \"\") {")
		g.P("      writer.writeString(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.BytesKind:
		g.P("    if (this.", fieldName, ".length > 0) {")
		g.P("      writer.writeBytes(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.MessageKind:
		g.P("    if (this.", fieldName, ") {")
		g.P("      writer.writeMessage(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	case protoreflect.EnumKind:
		g.P("    if (this.", fieldName, " !== 0) {")
		g.P("      writer.writeEnum(", fieldNumber, ", this.", fieldName, ");")
		g.P("    }")
	}
}

// GenerateRepeatedFieldSerialization generates repeated field serialization code
func GenerateRepeatedFieldSerialization(g *protogen.GeneratedFile, field *protogen.Field, file *protogen.File) {
	fieldNumber := field.Desc.Number()

	switch field.Desc.Kind() {
	case protoreflect.DoubleKind:
		g.P("      writer.writeDouble(", fieldNumber, ", item);")
	case protoreflect.FloatKind:
		g.P("      writer.writeFloat(", fieldNumber, ", item);")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("      writer.writeInt32(", fieldNumber, ", item);")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("      writer.writeInt64(", fieldNumber, ", item);")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("      writer.writeUint32(", fieldNumber, ", item);")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("      writer.writeUint64(", fieldNumber, ", item);")
	case protoreflect.BoolKind:
		g.P("      writer.writeBool(", fieldNumber, ", item);")
	case protoreflect.StringKind:
		g.P("      writer.writeString(", fieldNumber, ", item);")
	case protoreflect.BytesKind:
		g.P("      writer.writeBytes(", fieldNumber, ", item);")
	case protoreflect.MessageKind:
		g.P("      writer.writeMessage(", fieldNumber, ", item);")
	case protoreflect.EnumKind:
		g.P("      writer.writeEnum(", fieldNumber, ", item);")
	}
}

// GenerateFieldDeserializationWithWireType generates field deserialization with wire type checking
func GenerateFieldDeserializationWithWireType(g *protogen.GeneratedFile, field *protogen.Field, file *protogen.File) {
	fieldName := ToCamelCase(field.GoName)

	// Handle repeated fields
	if field.Desc.IsList() {
		// For message, string, and bytes types, each element is a separate tag+length+data
		// They are NEVER packed. Each occurrence of the field adds one item.
		if field.Desc.Kind() == protoreflect.MessageKind {
			g.P("          if (wireType === 2) { // Length-delimited")
			implType := types.GetMessageImplTypeName(field.Message, file)
			g.P("            message.", fieldName, ".push(reader.readMessage(", implType, ".deserializeBinary));")
			g.P("          } else {")
			g.P("            reader.skipField(wireType);")
			g.P("          }")
			return
		}
		if field.Desc.Kind() == protoreflect.StringKind {
			g.P("          if (wireType === 2) { // Length-delimited")
			g.P("            message.", fieldName, ".push(reader.readString());")
			g.P("          } else {")
			g.P("            reader.skipField(wireType);")
			g.P("          }")
			return
		}
		if field.Desc.Kind() == protoreflect.BytesKind {
			g.P("          if (wireType === 2) { // Length-delimited")
			g.P("            message.", fieldName, ".push(reader.readBytes());")
			g.P("          } else {")
			g.P("            reader.skipField(wireType);")
			g.P("          }")
			return
		}
		// For scalar types, proto3 uses packed encoding by default (all values in one length-delimited blob)
		g.P("          if (wireType === 2) { // Length-delimited (packed)")
		g.P("            const length = reader.readVarint();")
		g.P("            const endPos = reader.position + length;")
		g.P("            while (reader.position < endPos) {")
		GenerateRepeatedFieldItem(g, field, file)
		g.P("            }")
		g.P("          } else {")
		// Also handle non-packed encoding (wire type 0 for varints)
		g.P("            // Non-packed encoding - single item")
		GenerateRepeatedFieldItemNonPacked(g, field, file)
		g.P("          }")
		return
	}

	// Handle map fields
	if field.Desc.IsMap() {
		g.P("          if (wireType === 2) { // Length-delimited")
		g.P("            const length = reader.readVarint();")
		g.P("            const endPos = reader.position + length;")
		g.P("            while (reader.position < endPos) {")
		g.P("              const entryLength = reader.readVarint();")
		g.P("              const entryEndPos = reader.position + entryLength;")
		g.P("              let key, value;")
		g.P("              while (reader.position < entryEndPos) {")
		g.P("                const entryTag = reader.readVarint();")
		g.P("                const entryFieldNumber = entryTag >>> 3;")
		g.P("                const entryWireType = entryTag & 7;")
		g.P("                if (entryFieldNumber === 1) {")
		GenerateMapKeyDeserialization(g, field, file)
		g.P("                } else if (entryFieldNumber === 2) {")
		GenerateMapValueDeserialization(g, field, file)
		g.P("                } else {")
		g.P("                  reader.skipField(entryWireType);")
		g.P("                }")
		g.P("              }")
		g.P("              if (key !== undefined && value !== undefined) {")
		g.P("                message.", fieldName, ".set(key, value);")
		g.P("              }")
		g.P("            }")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
		return
	}

	// Handle regular fields with wire type validation
	switch field.Desc.Kind() {
	case protoreflect.DoubleKind:
		g.P("          if (wireType === 1) { // 64-bit")
		g.P("            message.", fieldName, " = reader.readDouble();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.FloatKind:
		g.P("          if (wireType === 5) { // 32-bit")
		g.P("            message.", fieldName, " = reader.readFloat();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("          if (wireType === 0) { // Varint")
		g.P("            message.", fieldName, " = reader.readInt32();")
		g.P("          } else if (wireType === 5) { // 32-bit")
		g.P("            message.", fieldName, " = reader.readInt32Fixed();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("          if (wireType === 0) { // Varint")
		g.P("            message.", fieldName, " = reader.readInt64();")
		g.P("          } else if (wireType === 1) { // 64-bit")
		g.P("            message.", fieldName, " = reader.readInt64Fixed();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("          if (wireType === 0) { // Varint")
		g.P("            message.", fieldName, " = reader.readUint32();")
		g.P("          } else if (wireType === 5) { // 32-bit")
		g.P("            message.", fieldName, " = reader.readUint32Fixed();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("          if (wireType === 0) { // Varint")
		g.P("            message.", fieldName, " = reader.readUint64();")
		g.P("          } else if (wireType === 1) { // 64-bit")
		g.P("            message.", fieldName, " = reader.readUint64Fixed();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.BoolKind:
		g.P("          if (wireType === 0) { // Varint")
		g.P("            message.", fieldName, " = reader.readBool();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.StringKind:
		g.P("          if (wireType === 2) { // Length-delimited")
		g.P("            message.", fieldName, " = reader.readString();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.BytesKind:
		g.P("          if (wireType === 2) { // Length-delimited")
		g.P("            message.", fieldName, " = reader.readBytes();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.MessageKind:
		g.P("          if (wireType === 2) { // Length-delimited")
		implType := types.GetMessageImplTypeName(field.Message, file)
		g.P("            message.", fieldName, " = reader.readMessage(", implType, ".deserializeBinary);")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	case protoreflect.EnumKind:
		g.P("          if (wireType === 0) { // Varint")
		g.P("            message.", fieldName, " = reader.readEnum();")
		g.P("          } else {")
		g.P("            reader.skipField(wireType);")
		g.P("          }")
	}
}

// GenerateRepeatedFieldItem generates repeated field item deserialization (for packed encoding)
func GenerateRepeatedFieldItem(g *protogen.GeneratedFile, field *protogen.Field, file *protogen.File) {
	switch field.Desc.Kind() {
	case protoreflect.DoubleKind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readDouble());")
	case protoreflect.FloatKind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readFloat());")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readInt32());")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readInt64());")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readUint32());")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readUint64());")
	case protoreflect.BoolKind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readBool());")
	case protoreflect.StringKind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readString());")
	case protoreflect.BytesKind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readBytes());")
	case protoreflect.MessageKind:
		implType := types.GetMessageImplTypeName(field.Message, file)
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readMessage(", implType, ".deserializeBinary));")
	case protoreflect.EnumKind:
		g.P("              message.", ToCamelCase(field.GoName), ".push(reader.readEnum());")
	}
}

// GenerateRepeatedFieldItemNonPacked generates repeated field item deserialization for non-packed encoding
func GenerateRepeatedFieldItemNonPacked(g *protogen.GeneratedFile, field *protogen.Field, file *protogen.File) {
	fieldName := ToCamelCase(field.GoName)
	switch field.Desc.Kind() {
	case protoreflect.DoubleKind:
		g.P("            if (wireType === 1) { message.", fieldName, ".push(reader.readDouble()); }")
	case protoreflect.FloatKind:
		g.P("            if (wireType === 5) { message.", fieldName, ".push(reader.readFloat()); }")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("            if (wireType === 0) { message.", fieldName, ".push(reader.readInt32()); }")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("            if (wireType === 0) { message.", fieldName, ".push(reader.readInt64()); }")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("            if (wireType === 0) { message.", fieldName, ".push(reader.readUint32()); }")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("            if (wireType === 0) { message.", fieldName, ".push(reader.readUint64()); }")
	case protoreflect.BoolKind:
		g.P("            if (wireType === 0) { message.", fieldName, ".push(reader.readBool()); }")
	case protoreflect.EnumKind:
		g.P("            if (wireType === 0) { message.", fieldName, ".push(reader.readEnum()); }")
	}
}

// GenerateMapKeyDeserialization generates map key deserialization
func GenerateMapKeyDeserialization(g *protogen.GeneratedFile, field *protogen.Field, file *protogen.File) {
	keyField := field.Desc.MapKey()
	switch keyField.Kind() {
	case protoreflect.StringKind:
		g.P("                  key = reader.readString();")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("                  key = reader.readInt32();")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("                  key = reader.readInt64();")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("                  key = reader.readUint32();")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("                  key = reader.readUint64();")
	case protoreflect.BoolKind:
		g.P("                  key = reader.readBool();")
	}
}

// GenerateMapValueDeserialization generates map value deserialization
func GenerateMapValueDeserialization(g *protogen.GeneratedFile, field *protogen.Field, file *protogen.File) {
	valueField := field.Desc.MapValue()
	switch valueField.Kind() {
	case protoreflect.DoubleKind:
		g.P("                  value = reader.readDouble();")
	case protoreflect.FloatKind:
		g.P("                  value = reader.readFloat();")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("                  value = reader.readInt32();")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("                  value = reader.readInt64();")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("                  value = reader.readUint32();")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("                  value = reader.readUint64();")
	case protoreflect.BoolKind:
		g.P("                  value = reader.readBool();")
	case protoreflect.StringKind:
		g.P("                  value = reader.readString();")
	case protoreflect.BytesKind:
		g.P("                  value = reader.readBytes();")
	case protoreflect.MessageKind:
		implType := types.GetMessageImplTypeName(field.Message, file)
		g.P("                  value = reader.readMessage(", implType, ".deserializeBinary);")
	case protoreflect.EnumKind:
		g.P("                  value = reader.readEnum();")
	}
}

// GenerateImportsForTypesFile generates imports for external types
func GenerateImportsForTypesFile(g *protogen.GeneratedFile, file *protogen.File, externalTypes map[string]string, target string) {

	// Generate import statements
	for packageName, importPath := range externalTypes {
		g.P("import { ", packageName, " } from '", importPath, "';")
	}

	if len(externalTypes) > 0 {
		g.P()
	}
}

// collectExternalTypes recursively collects external types from messages
func collectExternalTypes(message *protogen.Message, currentFile *protogen.File, externalTypes map[string]string, target string) {
	for _, field := range message.Fields {
		if field.Desc.Kind() == protoreflect.MessageKind {
			fieldFile := field.Message.Desc.ParentFile()
			fieldPackageName := types.GetPackageNameFromDescriptor(fieldFile)
			currentPackageName := types.GetPackageNameFromDescriptor(currentFile.Desc)

			// Collect types from different packages or same package but different files
			if fieldPackageName != "" && (fieldPackageName != currentPackageName || fieldFile.Path() != currentFile.Desc.Path()) {
				// Generate relative import path
				importPath := generateImportPath(fieldFile, currentFile, target)
				externalTypes[fieldPackageName] = importPath
			}
		} else if field.Desc.Kind() == protoreflect.EnumKind {
			fieldFile := field.Enum.Desc.ParentFile()
			fieldPackageName := types.GetPackageNameFromDescriptor(fieldFile)
			currentPackageName := types.GetPackageNameFromDescriptor(currentFile.Desc)

			// Collect enum types from different packages or same package but different files
			if fieldPackageName != "" && (fieldPackageName != currentPackageName || fieldFile.Path() != currentFile.Desc.Path()) {
				// Generate relative import path
				importPath := generateImportPath(fieldFile, currentFile, target)
				externalTypes[fieldPackageName] = importPath
			}
		}
	}

	// Check nested messages
	for _, nestedMessage := range message.Messages {
		collectExternalTypes(nestedMessage, currentFile, externalTypes, target)
	}
}

// generateImportPath generates a relative import path
func generateImportPath(fromFile protoreflect.FileDescriptor, toFile *protogen.File, target string) string {
	fromPath := fromFile.Path()
	toPath := toFile.Desc.Path()

	// Remove .proto extension
	fromPath = strings.TrimSuffix(fromPath, ".proto")
	toPath = strings.TrimSuffix(toPath, ".proto")

	// Extract directory and filename
	fromDir := ""
	fromFileName := fromPath
	if lastSlash := strings.LastIndex(fromPath, "/"); lastSlash != -1 {
		fromDir = fromPath[:lastSlash]
		fromFileName = fromPath[lastSlash+1:]
	}

	toDir := ""
	if lastSlash := strings.LastIndex(toPath, "/"); lastSlash != -1 {
		toDir = toPath[:lastSlash]
	}

	// Determine the suffix based on target and whether the from file has services
	// Service files always use _pb.ts, type files use _pb.ts for Node.js, _types.ts for React Native
	suffix := "_types"
	if strings.Contains(fromFileName, "service") {
		suffix = "_pb"
	} else if target == "nodejs" || target == "node" {
		suffix = "_pb"
	}

	// If same directory, use relative import
	if fromDir == toDir {
		return "./" + fromFileName + suffix
	}

	// Different directories - use relative path
	// For NeoFS: accounting/service.proto importing from session/types.proto
	// Should be: ../session/types_types or ../session/types_pb

	// Extract the directory name from the from path
	dirName := fromFileName
	if fromDir != "" {
		// Get the directory name (e.g., "session" from "session/types.proto")
		dirName = fromDir
		if lastSlash := strings.LastIndex(fromDir, "/"); lastSlash != -1 {
			dirName = fromDir[lastSlash+1:]
		}
	}

	// Debug: print the paths
	// fmt.Printf("DEBUG: fromPath=%s, toPath=%s, fromDir=%s, toDir=%s, dirName=%s, fromFileName=%s\n", fromPath, toPath, fromDir, toDir, dirName, fromFileName)

	return "../" + dirName + "/" + fromFileName + suffix
}

// ToCamelCase converts a string to camelCase
func ToCamelCase(s string) string {
	if s == "" {
		return s
	}

	// Handle special cases
	switch s {
	case "v2":
		return "V2"
	case "v1":
		return "V1"
	default:
		// Capitalize first letter
		return strings.ToUpper(s[:1]) + s[1:]
	}
}
