package services

import (
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateNodeJSServicesFile generates the services TypeScript file for Node.js
func GenerateNodeJSServicesFile(gen *protogen.Plugin, file *protogen.File) {
	// Use the proto file path directly for output
	protoPath := file.Desc.Path()
	// Remove .proto extension and convert to output path
	// For Node.js, we generate service_grpc_pb.ts (matching protobuf.js naming convention)
	outputPath := strings.TrimSuffix(protoPath, ".proto") + "_grpc_pb.ts"
	g := gen.NewGeneratedFile(outputPath, file.GoImportPath)

	// Generate header
	g.P("// Code generated by protoc-gen-grpc-ts. DO NOT EDIT.")
	g.P("// Generated from: ", file.Desc.Path())
	g.P("// Target: nodejs")
	g.P()

	// Generate imports
	g.P("import * as grpc from '@grpc/grpc-js';")

	// Collect types used in service methods
	usedTypes := make(map[string]bool)
	for _, service := range file.Services {
		for _, method := range service.Methods {
			// Add request and response types
			usedTypes[method.Input.GoIdent.GoName] = true
			usedTypes[method.Output.GoIdent.GoName] = true
		}
	}

	// Generate import for types file with Impl classes
	// Extract proto filename for import path
	protoName := protoPath
	if lastSlash := strings.LastIndex(protoPath, "/"); lastSlash != -1 {
		protoName = protoPath[lastSlash+1:]
	}
	protoName = strings.TrimSuffix(protoName, ".proto")

	if len(usedTypes) > 0 {
		var typeList []string
		for typeName := range usedTypes {
			// Import the message classes (without Impl suffix - Node.js exports class aliases)
			typeList = append(typeList, typeName)
		}
		// Sort for consistent output
		sort.Strings(typeList)
		// Import from service_pb.ts (matching protobuf.js naming convention)
		g.P("import { ", strings.Join(typeList, ", "), " } from './", protoName, "_pb';")
	}
	g.P()

	// Generate service clients
	for _, service := range file.Services {
		GenerateNodeJSService(g, service, file)
	}
}

// GenerateNodeJSService generates a service client for Node.js
func GenerateNodeJSService(g *protogen.GeneratedFile, service *protogen.Service, file *protogen.File) {
	serviceName := service.GoName + "Client"

	g.P("export class ", serviceName, " {")
	g.P("  private client: grpc.Client;")
	g.P()
	g.P("  constructor(address: string, credentials: grpc.ChannelCredentials, options?: grpc.ChannelOptions) {")
	g.P("    this.client = new grpc.Client(address, credentials, options);")
	g.P("  }")
	g.P()

	for _, method := range service.Methods {
		GenerateNodeJSMethod(g, method, service)
	}

	g.P("  close(): void {")
	g.P("    this.client.close();")
	g.P("  }")
	g.P("}")
	g.P()
}

// GenerateNodeJSMethod generates a method in the Node.js service client
func GenerateNodeJSMethod(g *protogen.GeneratedFile, method *protogen.Method, service *protogen.Service) {
	methodName := strings.ToLower(method.GoName[:1]) + method.GoName[1:]
	// Use message class names without Impl suffix for Node.js compatibility
	inputType := method.Input.GoIdent.GoName
	outputType := method.Output.GoIdent.GoName
	methodPath := GetFullMethodName(service, method)

	// Generate method signature based on streaming type
	if method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer() {
		// Bidirectional streaming - returns ClientDuplexStream
		g.P("  ", methodName, "(metadata?: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientDuplexStream<", inputType, ", ", outputType, "> {")
		g.P("    return this.client.makeBidiStreamRequest<", inputType, ", ", outputType, ">(")
		g.P("      '", methodPath, "',")
		g.P("      (arg) => Buffer.from(arg.serializeBinary()),")
		g.P("      (buf) => ", outputType, ".deserializeBinary(new Uint8Array(buf)),")
		g.P("      metadata || new grpc.Metadata(),")
		g.P("      options || {}")
		g.P("    );")
		g.P("  }")
	} else if method.Desc.IsStreamingServer() {
		// Server streaming - returns ClientReadableStream
		g.P("  ", methodName, "(request: ", inputType, ", metadata?: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientReadableStream<", outputType, "> {")
		g.P("    return this.client.makeServerStreamRequest<", inputType, ", ", outputType, ">(")
		g.P("      '", methodPath, "',")
		g.P("      (arg) => Buffer.from(arg.serializeBinary()),")
		g.P("      (buf) => ", outputType, ".deserializeBinary(new Uint8Array(buf)),")
		g.P("      request,")
		g.P("      metadata || new grpc.Metadata(),")
		g.P("      options || {}")
		g.P("    );")
		g.P("  }")
	} else if method.Desc.IsStreamingClient() {
		// Client streaming - returns ClientWritableStream and takes callback for final response
		// The callback is required, but we provide a no-op default for convenience
		g.P("  ", methodName, "(metadata?: grpc.Metadata, options?: grpc.CallOptions, callback?: (error: grpc.ServiceError | null, response?: ", outputType, ") => void): grpc.ClientWritableStream<", inputType, "> {")
		g.P("    // Default to no-op callback if not provided")
		g.P("    const finalCallback = callback || ((err, response) => {")
		g.P("      if (err) {")
		g.P("        console.error('Client stream error:', err);")
		g.P("      }")
		g.P("    });")
		g.P()
		g.P("    return this.client.makeClientStreamRequest<", inputType, ", ", outputType, ">(")
		g.P("      '", methodPath, "',")
		g.P("      (arg) => Buffer.from(arg.serializeBinary()),")
		g.P("      (buf) => ", outputType, ".deserializeBinary(new Uint8Array(buf)),")
		g.P("      metadata || new grpc.Metadata(),")
		g.P("      options || {},")
		g.P("      finalCallback")
		g.P("    );")
		g.P("  }")
	} else {
		// Unary call
		g.P("  ", methodName, "(request: ", inputType, ", metadata?: grpc.Metadata, options?: grpc.CallOptions): Promise<", outputType, "> {")
		g.P("    return new Promise((resolve, reject) => {")
		g.P("      this.client.makeUnaryRequest<", inputType, ", ", outputType, ">(")
		g.P("        '", methodPath, "',")
		g.P("        (arg) => Buffer.from(arg.serializeBinary()),")
		g.P("        (buf) => ", outputType, ".deserializeBinary(new Uint8Array(buf)),")
		g.P("        request,")
		g.P("        metadata || new grpc.Metadata(),")
		g.P("        options || {},")
		g.P("        (err, response) => {")
		g.P("          if (err) {")
		g.P("            reject(err);")
		g.P("          } else {")
		g.P("            resolve(response!);")
		g.P("          }")
		g.P("        }")
		g.P("      );")
		g.P("    });")
		g.P("  }")
	}
	g.P()
}
