package services

import (
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateReactNativeServicesFile generates the services TypeScript file for React Native
func GenerateReactNativeServicesFile(gen *protogen.Plugin, file *protogen.File) {
	// Use the proto file path directly for output
	protoPath := file.Desc.Path()
	// Remove .proto extension and convert to output path
	outputPath := strings.TrimSuffix(protoPath, ".proto") + "_services.ts"
	g := gen.NewGeneratedFile(outputPath, file.GoImportPath)

	// Generate header
	g.P("// Code generated by protoc-gen-grpc-ts. DO NOT EDIT.")
	g.P("// Generated from: ", file.Desc.Path())
	g.P("// Target: react-native")
	g.P()

	// Generate imports
	g.P("import { GrpcClient } from 'grpc-react-native';")

	// Collect types used in service methods
	usedTypes := make(map[string]bool)
	for _, service := range file.Services {
		for _, method := range service.Methods {
			// Add request and response types
			usedTypes[method.Input.GoIdent.GoName] = true
			usedTypes[method.Output.GoIdent.GoName] = true
		}
	}

	// Generate import for types file with Impl classes
	// Extract proto filename for import path
	protoName := protoPath
	if lastSlash := strings.LastIndex(protoPath, "/"); lastSlash != -1 {
		protoName = protoPath[lastSlash+1:]
	}
	protoName = strings.TrimSuffix(protoName, ".proto")
	
	if len(usedTypes) > 0 {
		var typeList []string
		for typeName := range usedTypes {
			// Import the Impl classes, not the interfaces
			typeList = append(typeList, typeName+"Impl")
		}
		// Sort for consistent output
		sort.Strings(typeList)
		g.P("import { ", strings.Join(typeList, ", "), " } from './", protoName, "_types';")
	}
	g.P()

	// Generate service clients
	for _, service := range file.Services {
		GenerateService(g, service, file)
	}
}

// GenerateService generates a service client
func GenerateService(g *protogen.GeneratedFile, service *protogen.Service, file *protogen.File) {
	serviceName := service.GoName + "Client"
	packageName := GetPackageName(file)

	g.P("export class ", serviceName, " {")
	g.P("  constructor(private client: GrpcClient) {}")
	g.P()

	for _, method := range service.Methods {
		GenerateMethod(g, method, service, packageName)
	}

	g.P("}")
	g.P()
}

// GenerateMethod generates a method in the service client
func GenerateMethod(g *protogen.GeneratedFile, method *protogen.Method, service *protogen.Service, packageName string) {
	methodName := strings.ToLower(method.GoName[:1]) + method.GoName[1:]
	inputType := method.Input.GoIdent.GoName + "Impl"
	outputType := method.Output.GoIdent.GoName + "Impl"

	// Generate method signature based on streaming type
		if method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer() {
		// Bidirectional streaming
		g.P("  async* ", methodName, "(requests: AsyncIterable<", inputType, ">): AsyncGenerator<", outputType, "> {")
		g.P("    async function* serialize() {")
		g.P("      for await (const req of requests) {")
		g.P("        yield req.serializeBinary();")
		g.P("      }")
		g.P("    }")
		g.P("    const stream = this.client.bidirectionalStreamCall(")
		g.P("      '", GetFullMethodName(service, method), "',")
		g.P("      serialize()")
		g.P("    );")
		g.P("    for await (const response of stream) {")
		g.P("      if (response.done) {")
		g.P("        break; // End of stream")
		g.P("      }")
		g.P("      if (response.data) {")
		g.P("        yield ", outputType, ".deserializeBinary(response.data as Uint8Array);")
		g.P("      }")
		g.P("    }")
		g.P("  }")
	} else if method.Desc.IsStreamingServer() {
		// Server streaming
		g.P("  async* ", methodName, "(request: ", inputType, "): AsyncGenerator<", outputType, "> {")
		g.P("    const stream = this.client.serverStreamCall(")
		g.P("      '", GetFullMethodName(service, method), "',")
		g.P("      request.serializeBinary()")
		g.P("    );")
		g.P("    for await (const response of stream) {")
		g.P("      if (response.done) {")
		g.P("        break; // End of stream")
		g.P("      }")
		g.P("      if (response.data) {")
		g.P("        yield ", outputType, ".deserializeBinary(response.data as Uint8Array);")
		g.P("      }")
		g.P("    }")
		g.P("  }")
	} else if method.Desc.IsStreamingClient() {
		// Client streaming
		g.P("  async ", methodName, "(requests: AsyncIterable<", inputType, ">): Promise<", outputType, "> {")
		g.P("    async function* serialize() {")
		g.P("      for await (const req of requests) {")
		g.P("        yield req.serializeBinary();")
		g.P("      }")
		g.P("    }")
		g.P("    const response = await this.client.clientStreamCall(")
		g.P("      '", GetFullMethodName(service, method), "',")
		g.P("      serialize()")
		g.P("    );")
		g.P("    return ", outputType, ".deserializeBinary(response.data as Uint8Array);")
		g.P("  }")
	} else {
		// Unary call
		g.P("  async ", methodName, "(request: ", inputType, "): Promise<", outputType, "> {")
		g.P("    const response = await this.client.unaryCall(")
		g.P("      '", GetFullMethodName(service, method), "',")
		g.P("      request.serializeBinary()")
		g.P("    );")
		g.P("    return ", outputType, ".deserializeBinary(response.data as Uint8Array);")
		g.P("  }")
	}
	g.P()
}

// GetFullMethodName returns the full gRPC method name
func GetFullMethodName(service *protogen.Service, method *protogen.Method) string {
	return string(service.Desc.FullName()) + "/" + string(method.Desc.Name())
}

// GetPackageName extracts the package name from a proto file
func GetPackageName(file *protogen.File) string {
	packageName := string(file.Desc.Package())
	if packageName == "" {
		return ""
	}

	// Convert package name to TypeScript namespace format
	parts := strings.Split(packageName, ".")
	var result []string
	for _, part := range parts {
		if part != "" {
			result = append(result, ToCamelCase(part))
		}
	}
	return strings.Join(result, "")
}

// ToCamelCase converts a string to camelCase
func ToCamelCase(s string) string {
	if s == "" {
		return s
	}

	// Handle special cases
	switch s {
	case "v2":
		return "V2"
	case "v1":
		return "V1"
	default:
		// Capitalize first letter
		return strings.ToUpper(s[:1]) + s[1:]
	}
}
