package types

import (
	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateBinaryClasses generates the BinaryWriter and BinaryReader classes
func GenerateBinaryClasses(g *protogen.GeneratedFile) {
	// Generate BinaryWriter class
	g.P("class BinaryWriter {")
	g.P("  private buffer: Uint8Array = new Uint8Array(1024);")
	g.P("  private position: number = 0;")
	g.P()
	g.P("  private ensureCapacity(needed: number): void {")
	g.P("    if (this.position + needed > this.buffer.length) {")
	g.P("      const newBuffer = new Uint8Array(this.buffer.length * 2);")
	g.P("      newBuffer.set(this.buffer);")
	g.P("      this.buffer = newBuffer;")
	g.P("    }")
	g.P("  }")
	g.P()
	g.P("  private writeVarint(value: number): void {")
	g.P("    while (value > 127) {")
	g.P("      this.ensureCapacity(1);")
	g.P("      this.buffer[this.position++] = (value & 127) | 128;")
	g.P("      value >>>= 7;")
	g.P("    }")
	g.P("    this.ensureCapacity(1);")
	g.P("    this.buffer[this.position++] = value & 127;")
	g.P("  }")
	g.P()
	g.P("  private writeVarintBigInt(value: bigint): void {")
	g.P("    while (value > 127n) {")
	g.P("      this.ensureCapacity(1);")
	g.P("      this.buffer[this.position++] = Number(value & 127n) | 128;")
	g.P("      value >>= 7n;")
	g.P("    }")
	g.P("    this.ensureCapacity(1);")
	g.P("    this.buffer[this.position++] = Number(value & 127n);")
	g.P("  }")
	g.P()
	g.P("  writeDouble(fieldNumber: number, value: number): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 1); // wire type 1")
	g.P("    this.ensureCapacity(8);")
	g.P("    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 8);")
	g.P("    view.setFloat64(0, value, true); // little endian")
	g.P("    this.position += 8;")
	g.P("  }")
	g.P()
	g.P("  writeFloat(fieldNumber: number, value: number): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 5); // wire type 5")
	g.P("    this.ensureCapacity(4);")
	g.P("    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 4);")
	g.P("    view.setFloat32(0, value, true); // little endian")
	g.P("    this.position += 4;")
	g.P("  }")
	g.P()
	g.P("  writeInt32(fieldNumber: number, value: number): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 0); // wire type 0")
	g.P("    this.writeVarint(value);")
	g.P("  }")
	g.P()
	g.P("  writeInt64(fieldNumber: number, value: bigint): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 0); // wire type 0")
	g.P("    this.writeVarintBigInt(value);")
	g.P("  }")
	g.P()
	g.P("  writeUint32(fieldNumber: number, value: number): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 0); // wire type 0")
	g.P("    this.writeVarint(value);")
	g.P("  }")
	g.P()
	g.P("  writeUint64(fieldNumber: number, value: bigint): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 0); // wire type 0")
	g.P("    this.writeVarintBigInt(value);")
	g.P("  }")
	g.P()
	g.P("  writeBool(fieldNumber: number, value: boolean): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 0); // wire type 0")
	g.P("    this.writeVarint(value ? 1 : 0);")
	g.P("  }")
	g.P()
	g.P("  writeString(fieldNumber: number, value: string): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 2); // wire type 2")
	g.P("    const bytes = this.encodeString(value);")
	g.P("    this.writeVarint(bytes.length);")
	g.P("    this.ensureCapacity(bytes.length);")
	g.P("    this.buffer.set(bytes, this.position);")
	g.P("    this.position += bytes.length;")
	g.P("  }")
	g.P()
	g.P("  writeBytes(fieldNumber: number, value: Uint8Array): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 2); // wire type 2")
	g.P("    this.writeVarint(value.length);")
	g.P("    this.ensureCapacity(value.length);")
	g.P("    this.buffer.set(value, this.position);")
	g.P("    this.position += value.length;")
	g.P("  }")
	g.P()
	g.P("  writeMessage(fieldNumber: number, value: any): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 2); // wire type 2")
	g.P("    const bytes = value.serializeBinary();")
	g.P("    this.writeVarint(bytes.length);")
	g.P("    this.ensureCapacity(bytes.length);")
	g.P("    this.buffer.set(bytes, this.position);")
	g.P("    this.position += bytes.length;")
	g.P("  }")
	g.P()
	g.P("  writeEnum(fieldNumber: number, value: number): void {")
	g.P("    this.writeVarint((fieldNumber << 3) | 0); // wire type 0")
	g.P("    this.writeVarint(value);")
	g.P("  }")
	g.P()
	g.P("  private encodeString(str: string): Uint8Array {")
	g.P("    // Manual UTF-8 encoding (React Native compatible)")
	g.P("    const bytes: number[] = [];")
	g.P("    for (let i = 0; i < str.length; i++) {")
	g.P("      let codePoint = str.charCodeAt(i);")
	g.P("      if (codePoint >= 0xD800 && codePoint <= 0xDBFF && i + 1 < str.length) {")
	g.P("        const next = str.charCodeAt(i + 1);")
	g.P("        if (next >= 0xDC00 && next <= 0xDFFF) {")
	g.P("          codePoint = 0x10000 + ((codePoint - 0xD800) << 10) + (next - 0xDC00);")
	g.P("          i++;")
	g.P("        }")
	g.P("      }")
	g.P("      if (codePoint < 0x80) {")
	g.P("        bytes.push(codePoint);")
	g.P("      } else if (codePoint < 0x800) {")
	g.P("        bytes.push(0xC0 | (codePoint >> 6), 0x80 | (codePoint & 0x3F));")
	g.P("      } else if (codePoint < 0x10000) {")
	g.P("        bytes.push(0xE0 | (codePoint >> 12), 0x80 | ((codePoint >> 6) & 0x3F), 0x80 | (codePoint & 0x3F));")
	g.P("      } else {")
	g.P("        bytes.push(0xF0 | (codePoint >> 18), 0x80 | ((codePoint >> 12) & 0x3F), 0x80 | ((codePoint >> 6) & 0x3F), 0x80 | (codePoint & 0x3F));")
	g.P("      }")
	g.P("    }")
	g.P("    return new Uint8Array(bytes);")
	g.P("  }")
	g.P()
	g.P("  getResultBuffer(): Uint8Array {")
	g.P("    return this.buffer.slice(0, this.position);")
	g.P("  }")
	g.P("}")
	g.P()

	// Generate BinaryReader class
	g.P("class BinaryReader {")
	g.P("  buffer: Uint8Array;")
	g.P("  position: number = 0;")
	g.P()
	g.P("  constructor(data: Uint8Array) {")
	g.P("    this.buffer = data;")
	g.P("  }")
	g.P()
	g.P("  readVarint(): number {")
	g.P("    let result = 0;")
	g.P("    let shift = 0;")
	g.P("    while (this.position < this.buffer.length) {")
	g.P("      const byte = this.buffer[this.position++];")
	g.P("      result |= (byte & 127) << shift;")
	g.P("      if ((byte & 128) === 0) break;")
	g.P("      shift += 7;")
	g.P("    }")
	g.P("    return result;")
	g.P("  }")
	g.P()
	g.P("  readVarintBigInt(): bigint {")
	g.P("    let result = 0n;")
	g.P("    let shift = 0n;")
	g.P("    while (this.position < this.buffer.length) {")
	g.P("      const byte = BigInt(this.buffer[this.position++]);")
	g.P("      result |= (byte & 127n) << shift;")
	g.P("      if ((byte & 128n) === 0n) break;")
	g.P("      shift += 7n;")
	g.P("    }")
	g.P("    return result;")
	g.P("  }")
	g.P()
	g.P("  readDouble(): number {")
	g.P("    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 8);")
	g.P("    this.position += 8;")
	g.P("    return view.getFloat64(0, true); // little endian")
	g.P("  }")
	g.P()
	g.P("  readFloat(): number {")
	g.P("    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 4);")
	g.P("    this.position += 4;")
	g.P("    return view.getFloat32(0, true); // little endian")
	g.P("  }")
	g.P()
	g.P("  readInt32(): number {")
	g.P("    return this.readVarint();")
	g.P("  }")
	g.P()
	g.P("  readInt64(): bigint {")
	g.P("    return this.readVarintBigInt();")
	g.P("  }")
	g.P()
	g.P("  readUint32(): number {")
	g.P("    return this.readVarint();")
	g.P("  }")
	g.P()
	g.P("  readUint64(): bigint {")
	g.P("    return this.readVarintBigInt();")
	g.P("  }")
	g.P()
	g.P("  readBool(): boolean {")
	g.P("    return this.readVarint() !== 0;")
	g.P("  }")
	g.P()
	g.P("  readString(): string {")
	g.P("    const length = this.readVarint();")
	g.P("    const bytes = this.buffer.slice(this.position, this.position + length);")
	g.P("    this.position += length;")
	g.P("    return this.decodeString(bytes);")
	g.P("  }")
	g.P()
	g.P("  private decodeString(bytes: Uint8Array): string {")
	g.P("    // Manual UTF-8 decoding (React Native compatible)")
	g.P("    let result = '';")
	g.P("    let i = 0;")
	g.P("    while (i < bytes.length) {")
	g.P("      const byte1 = bytes[i++];")
	g.P("      if (byte1 < 0x80) {")
	g.P("        result += String.fromCharCode(byte1);")
	g.P("      } else if ((byte1 & 0xE0) === 0xC0) {")
	g.P("        const byte2 = bytes[i++] & 0x3F;")
	g.P("        result += String.fromCharCode(((byte1 & 0x1F) << 6) | byte2);")
	g.P("      } else if ((byte1 & 0xF0) === 0xE0) {")
	g.P("        const byte2 = bytes[i++] & 0x3F;")
	g.P("        const byte3 = bytes[i++] & 0x3F;")
	g.P("        result += String.fromCharCode(((byte1 & 0x0F) << 12) | (byte2 << 6) | byte3);")
	g.P("      } else if ((byte1 & 0xF8) === 0xF0) {")
	g.P("        const byte2 = bytes[i++] & 0x3F;")
	g.P("        const byte3 = bytes[i++] & 0x3F;")
	g.P("        const byte4 = bytes[i++] & 0x3F;")
	g.P("        const codePoint = ((byte1 & 0x07) << 18) | (byte2 << 12) | (byte3 << 6) | byte4;")
	g.P("        result += String.fromCharCode(0xD800 + ((codePoint - 0x10000) >> 10), 0xDC00 + ((codePoint - 0x10000) & 0x3FF));")
	g.P("      }")
	g.P("    }")
	g.P("    return result;")
	g.P("  }")
	g.P()
	g.P("  readBytes(): Uint8Array {")
	g.P("    const length = this.readVarint();")
	g.P("    const bytes = this.buffer.slice(this.position, this.position + length);")
	g.P("    this.position += length;")
	g.P("    return bytes;")
	g.P("  }")
	g.P()
	g.P("  readMessage<T>(deserialize: (data: Uint8Array) => T): T {")
	g.P("    const length = this.readVarint();")
	g.P("    const bytes = this.buffer.slice(this.position, this.position + length);")
	g.P("    this.position += length;")
	g.P("    return deserialize(bytes);")
	g.P("  }")
	g.P()
	g.P("  readEnum(): number {")
	g.P("    return this.readVarint();")
	g.P("  }")
	g.P()
	g.P("  readInt32Fixed(): number {")
	g.P("    const bytes = this.buffer.slice(this.position, this.position + 4);")
	g.P("    this.position += 4;")
	g.P("    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);")
	g.P("    return view.getInt32(0, true); // little-endian")
	g.P("  }")
	g.P()
	g.P("  readInt64Fixed(): bigint {")
	g.P("    const bytes = this.buffer.slice(this.position, this.position + 8);")
	g.P("    this.position += 8;")
	g.P("    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);")
	g.P("    return view.getBigInt64(0, true); // little-endian")
	g.P("  }")
	g.P()
	g.P("  readUint32Fixed(): number {")
	g.P("    const bytes = this.buffer.slice(this.position, this.position + 4);")
	g.P("    this.position += 4;")
	g.P("    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);")
	g.P("    return view.getUint32(0, true); // little-endian")
	g.P("  }")
	g.P()
	g.P("  readUint64Fixed(): bigint {")
	g.P("    const bytes = this.buffer.slice(this.position, this.position + 8);")
	g.P("    this.position += 8;")
	g.P("    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);")
	g.P("    return view.getBigUint64(0, true); // little-endian")
	g.P("  }")
	g.P()
	g.P("  skipField(wireType: number): void {")
	g.P("    switch (wireType) {")
	g.P("      case 0: // Varint")
	g.P("        this.readVarint();")
	g.P("        break;")
	g.P("      case 1: // 64-bit")
	g.P("        this.position += 8;")
	g.P("        break;")
	g.P("      case 2: // Length-delimited")
	g.P("        const length = this.readVarint();")
	g.P("        this.position += length;")
	g.P("        break;")
	g.P("      case 3: // Start group (deprecated, just skip)")
	g.P("        // Groups are deprecated in proto3, skip without reading")
	g.P("        break;")
	g.P("      case 4: // End group (deprecated, just skip)")
	g.P("        // Groups are deprecated in proto3, skip without reading")
	g.P("        break;")
	g.P("      case 5: // 32-bit")
	g.P("        this.position += 4;")
	g.P("        break;")
	g.P("      default:")
	g.P("        throw new Error(`Unknown wire type: ${wireType}`);")
	g.P("    }")
	g.P("  }")
	g.P("}")
	g.P()
}
